// Yoke Domain Intelligence — PDF Report Generator
// Uses pdf-lib for pure-JS PDF generation (CF Worker compatible)
// Ported from yoke-pdf-demo/generate.js

import fontkit from "@pdf-lib/fontkit";
import { type Color, PDFDocument, type PDFFont, type PDFPage, rgb } from "pdf-lib";
import { AXIS_WEIGHTS as CANONICAL_AXIS_WEIGHTS, TIER_THRESHOLDS } from "./config/signal-registry";
import type { PdfFontData } from "./pdf-fonts";

// ─── Self-Hoster Customization ─────────────────────────────────────
const REPORT_CONFIG = {
  brandName: "YOKE",
  brandTagline: "Domain Intelligence Report",
  footerText: "Generated by yoke.lol — open-source domain intelligence",
  footerUrl: "yoke.lol",
  showLogo: true,
};

// ─── Types ─────────────────────────────────────────────────────────

interface Fonts {
  regular: PDFFont;
  medium: PDFFont;
  semibold: PDFFont;
  bold: PDFFont;
  mono: PDFFont;
}

// biome-ignore lint/suspicious/noExplicitAny: analysis data is loosely typed
type AnalysisData = any;

interface DrawRectOpts {
  fill?: Color;
  border?: Color;
  borderWidth?: number;
  opacity?: number;
  borderOpacity?: number;
}

// ─── Color System ──────────────────────────────────────────────────
const COLORS = {
  bg: rgb(1, 1, 1),
  surface: rgb(0.965, 0.973, 0.98),
  border: rgb(0.82, 0.851, 0.878),
  text: rgb(0.122, 0.137, 0.157),
  textSecondary: rgb(0.349, 0.388, 0.431),
  dim: rgb(0.431, 0.467, 0.506),
  accent: rgb(0.118, 0.227, 0.373),
  accentLight: rgb(0.118, 0.227, 0.373),
  excellent: rgb(0.102, 0.498, 0.216),
  strong: rgb(0.035, 0.412, 0.855),
  moderate: rgb(0.749, 0.529, 0.0),
  weak: rgb(0.812, 0.133, 0.18),
  critical: rgb(0.643, 0.055, 0.149),
  good: rgb(0.102, 0.498, 0.216),
  info: rgb(0.035, 0.412, 0.855),
  low: rgb(0.749, 0.529, 0.0),
  medium: rgb(0.812, 0.133, 0.18),
  high: rgb(0.812, 0.133, 0.18),
  absent: rgb(0.431, 0.467, 0.506),
  white: rgb(1, 1, 1),
};

function severityColor(severity: string | undefined): Color {
  if (severity === "good") return COLORS.good;
  if (severity === "info") return COLORS.info;
  if (severity === "low") return COLORS.moderate;
  if (severity === "medium") return COLORS.weak;
  if (severity === "high") return COLORS.weak;
  if (severity === "critical") return COLORS.critical;
  if (severity === "absent") return COLORS.absent;
  return COLORS.textSecondary;
}

function tierColor(tier: string): Color {
  const t = (tier || "").toLowerCase();
  if (t === "excellent") return COLORS.excellent;
  if (t === "strong") return COLORS.strong;
  if (t === "moderate") return COLORS.moderate;
  if (t === "weak") return COLORS.weak;
  if (t === "critical") return COLORS.critical;
  return COLORS.textSecondary;
}

function tierFromScore(score: number | null | undefined): string {
  if (score == null) return "N/A";
  for (const { tier, min } of TIER_THRESHOLDS) {
    if (score >= min) return tier;
  }
  return "Critical";
}

// Build TIER_DEFS from canonical TIER_THRESHOLDS for PDF rendering
const TIER_COLORS: Record<string, typeof COLORS.excellent> = {
  Excellent: COLORS.excellent,
  Strong: COLORS.strong,
  Moderate: COLORS.moderate,
  Weak: COLORS.weak,
  Critical: COLORS.critical,
};
const TIER_DEFS = TIER_THRESHOLDS.slice()
  .reverse()
  .map((t, i, arr) => ({
    tier: t.tier,
    min: t.min,
    max: i < arr.length - 1 ? arr[i + 1].min : 100,
    color: TIER_COLORS[t.tier] ?? COLORS.textSecondary,
  }));

const AXIS_LABELS: Record<string, string> = {
  security: "Security",
  speed: "Speed",
  foundations: "Foundations",
  reputation: "Reputation",
  discoverability: "Discoverability",
  email: "Email",
};

const AXIS_ABBR: Record<string, string> = {
  security: "SEC",
  speed: "SPD",
  foundations: "FND",
  reputation: "REP",
  discoverability: "DIS",
  email: "EML",
};

// Use canonical axis weights from signal registry
const AXIS_WEIGHTS: Record<string, number> = { ...CANONICAL_AXIS_WEIGHTS };

const AXIS_ORDER = ["security", "speed", "foundations", "reputation", "discoverability", "email"];

const CWV_EXPLAINERS: Record<string, string> = {
  LCP: "Largest Contentful Paint — how fast the main content loads",
  FCP: "First Contentful Paint — time to first visual response",
  CLS: "Cumulative Layout Shift — visual stability score",
  TBT: "Total Blocking Time — main thread responsiveness",
  TTFB: "Time to First Byte — server response speed",
};

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 54;
const CONTENT_W = PAGE_W - 2 * MARGIN;
const HEADER_H = 30;
const FOOTER_H = 24;
const CONTENT_TOP = PAGE_H - MARGIN - HEADER_H - 8;
const CONTENT_BOTTOM = MARGIN + FOOTER_H + 8;

// ─── Text Helpers ────────────────────────────────────────────────

function textWidth(font: PDFFont, text: string, size: number): number {
  try {
    return font.widthOfTextAtSize(text, size);
  } catch {
    let w = 0;
    for (const ch of text) {
      try {
        w += font.widthOfTextAtSize(ch, size);
      } catch {
        w += size * 0.5;
      }
    }
    return w;
  }
}

function truncateText(font: PDFFont, text: string, size: number, maxWidth: number): string {
  if (!text) return "";
  const str = String(text);
  if (textWidth(font, str, size) <= maxWidth) return str;
  let truncated = str;
  while (truncated.length > 1 && textWidth(font, `${truncated}...`, size) > maxWidth) {
    truncated = truncated.slice(0, -1);
  }
  return `${truncated}...`;
}

function wrapText(font: PDFFont, text: string, size: number, maxWidth: number): string[] {
  if (!text) return [""];
  const str = String(text);
  const words = str.split(/\s+/);
  const lines: string[] = [];
  let currentLine = "";
  for (const word of words) {
    if (textWidth(font, word, size) > maxWidth) {
      if (currentLine) {
        lines.push(currentLine);
        currentLine = "";
      }
      let remaining = word;
      while (remaining.length > 0) {
        let fit = "";
        for (let i = 1; i <= remaining.length; i++) {
          const sub = remaining.slice(0, i);
          if (textWidth(font, sub, size) > maxWidth) break;
          fit = sub;
        }
        if (!fit) fit = remaining.slice(0, 1);
        lines.push(fit);
        remaining = remaining.slice(fit.length);
      }
      continue;
    }
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    if (textWidth(font, testLine, size) <= maxWidth) {
      currentLine = testLine;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines.length ? lines : [""];
}

function safeText(text: string | number | null | undefined): string {
  if (!text && text !== 0) return "";
  // biome-ignore lint/suspicious/noControlCharactersInRegex: intentionally stripping control characters
  return String(text).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "");
}

// ─── Drawing Helpers ─────────────────────────────────────────────

function drawText(
  page: PDFPage,
  text: string | number | null | undefined,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  color: Color,
  options: { maxWidth?: number; wrap?: boolean } = {},
): void {
  const str = safeText(text);
  if (!str) return;
  const maxWidth = options.maxWidth || CONTENT_W - (x - MARGIN);
  const display = options.wrap ? str : truncateText(font, str, size, maxWidth);
  try {
    page.drawText(display, { x, y, size, font, color });
  } catch {
    const safe = display.replace(/[^\x20-\x7E]/g, "?");
    page.drawText(safe, { x, y, size, font, color });
  }
}

function drawRect(page: PDFPage, x: number, y: number, w: number, h: number, options: DrawRectOpts = {}): void {
  page.drawRectangle({
    x,
    y,
    width: w,
    height: h,
    color: options.fill,
    borderColor: options.border,
    borderWidth: options.borderWidth || (options.border ? 1 : 0),
    opacity: options.opacity,
    borderOpacity: options.borderOpacity,
  });
}

function drawLine(page: PDFPage, x1: number, y1: number, x2: number, y2: number, color: Color, width = 1): void {
  page.drawLine({ start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, color, thickness: width });
}

// ─── Page Header / Footer ────────────────────────────────────────

function drawPageHeader(page: PDFPage, fonts: Fonts, pageLabel?: string): void {
  const y = PAGE_H - MARGIN;
  drawText(page, REPORT_CONFIG.brandName, MARGIN, y - 12, fonts.bold, 12, COLORS.accent);
  const rightText = pageLabel || REPORT_CONFIG.brandTagline;
  const rw = textWidth(fonts.regular, rightText, 10);
  drawText(page, rightText, PAGE_W - MARGIN - rw, y - 11, fonts.regular, 10, COLORS.dim);
  drawLine(page, MARGIN, y - 18, PAGE_W - MARGIN, y - 18, COLORS.accent, 0.75);
}

function drawPageFooter(page: PDFPage, fonts: Fonts, pageNum: number, totalPages: number): void {
  const y = MARGIN;
  drawLine(page, MARGIN, y + FOOTER_H, PAGE_W - MARGIN, y + FOOTER_H, COLORS.accent, 0.75);
  drawText(page, REPORT_CONFIG.footerText, MARGIN, y + 6, fonts.regular, 8, COLORS.dim);
  const pageText = `Page ${pageNum} of ${totalPages}`;
  const pw = textWidth(fonts.regular, pageText, 8);
  drawText(page, pageText, PAGE_W - MARGIN - pw, y + 6, fonts.regular, 8, COLORS.dim);
}

// ─── Radar Chart ─────────────────────────────────────────────────

function drawRadarChart(page: PDFPage, fonts: Fonts, axes: AnalysisData, cx: number, cy: number, radius: number): void {
  const axisKeys = Object.keys(axes);
  const n = axisKeys.length;
  const angleStep = (2 * Math.PI) / n;
  const startAngle = -Math.PI / 2;

  // Grid rings
  for (const ring of [25, 50, 75, 100]) {
    const r = (ring / 100) * radius;
    const points = [];
    for (let i = 0; i < n; i++) {
      const angle = startAngle + i * angleStep;
      points.push({ x: cx + r * Math.cos(angle), y: cy + r * Math.sin(angle) });
    }
    for (let i = 0; i < n; i++) {
      const next = (i + 1) % n;
      drawLine(page, points[i].x, points[i].y, points[next].x, points[next].y, rgb(0.88, 0.9, 0.92), 0.5);
    }
  }

  // Axis lines
  for (let i = 0; i < n; i++) {
    const angle = startAngle + i * angleStep;
    const ex = cx + radius * Math.cos(angle);
    const ey = cy + radius * Math.sin(angle);
    drawLine(page, cx, cy, ex, ey, rgb(0.88, 0.9, 0.92), 0.5);
  }

  // Data polygon — navy accent fill
  const dataPoints = [];
  for (let i = 0; i < n; i++) {
    const score = axes[axisKeys[i]]?.score ?? 0;
    const r = (score / 100) * radius;
    const angle = startAngle + i * angleStep;
    dataPoints.push({ x: cx + r * Math.cos(angle), y: cy + r * Math.sin(angle) });
  }

  if (dataPoints.length >= 3) {
    const p0 = dataPoints[0];
    let svgPath = "M 0,0";
    for (let i = 1; i < dataPoints.length; i++) {
      svgPath += ` L ${(dataPoints[i].x - p0.x).toFixed(2)},${-(dataPoints[i].y - p0.y).toFixed(2)}`;
    }
    svgPath += " Z";

    page.drawSvgPath(svgPath, {
      x: p0.x,
      y: p0.y,
      color: COLORS.accent,
      opacity: 0.15,
      borderColor: COLORS.accent,
      borderWidth: 2,
      borderOpacity: 0.8,
    });

    for (const pt of dataPoints) {
      page.drawCircle({ x: pt.x, y: pt.y, size: 2.5, color: COLORS.accent });
    }
  }

  // Axis labels — OUTSIDE the grid with generous padding
  const labelPadding = 36; // distance beyond the outermost ring
  for (let i = 0; i < n; i++) {
    const angle = startAngle + i * angleStep;
    const label = AXIS_LABELS[axisKeys[i]] || axisKeys[i];
    const score = axes[axisKeys[i]]?.score ?? 0;
    const labelText = `${label} (${score})`;
    const tw = textWidth(fonts.regular, labelText, 7.5);
    const labelR = radius + labelPadding;
    const lx = cx + labelR * Math.cos(angle);
    const ly = cy + labelR * Math.sin(angle);

    let textX: number;
    let textY: number;
    const cosA = Math.cos(angle);
    const sinA = Math.sin(angle);

    if (sinA < -0.3) {
      // Top labels
      textX = lx - tw / 2;
      textY = ly + 10;
    } else if (sinA > 0.3) {
      // Bottom labels
      textX = lx - tw / 2;
      textY = ly - 16;
    } else if (cosA < 0) {
      textX = lx - tw - 6;
      textY = ly - 4;
    } else {
      textX = lx + 6;
      textY = ly - 4;
    }

    textX = Math.max(MARGIN, Math.min(textX, PAGE_W - MARGIN - tw));
    drawText(page, labelText, textX, textY, fonts.regular, 7.5, COLORS.textSecondary, { maxWidth: 130 });
  }
}

// ─── Summary Card (2-col key-value) ──────────────────────────────

function drawSummaryCard(page: PDFPage, fonts: Fonts, x: number, y: number, w: number, rows: string[][]): number {
  const rowH = 18;
  const padding = 10;
  const h = rows.length * rowH + padding * 2;
  const colW = (w - padding * 2) / 2;

  drawRect(page, x, y - h, w, h, { fill: COLORS.surface, border: COLORS.border, borderWidth: 0.5 });

  let cy = y - padding - 12;
  for (const row of rows) {
    for (let c = 0; c < 2; c++) {
      const cell = row[c];
      if (!cell) continue;
      const cellX = x + padding + c * colW;
      const parts = cell.split(": ");
      if (parts.length >= 2) {
        const label = `${parts[0]}: `;
        const value = parts.slice(1).join(": ");
        drawText(page, label, cellX, cy, fonts.medium, 9, COLORS.textSecondary, { maxWidth: colW - 10 });
        const lw = textWidth(fonts.medium, label, 9);
        drawText(page, value, cellX + lw, cy, fonts.regular, 9, COLORS.text, { maxWidth: colW - lw - 10 });
      } else {
        drawText(page, cell, cellX, cy, fonts.regular, 9, COLORS.text, { maxWidth: colW - 10 });
      }
    }
    cy -= rowH;
  }
  return h;
}

// ─── Data Table ──────────────────────────────────────────────────

interface DataTableOptions {
  rowHeight?: number;
  fontSize?: number;
}

interface DataTableCell {
  text: string;
  color: Color;
}

function drawDataTable(
  page: PDFPage,
  fonts: Fonts,
  x: number,
  y: number,
  w: number,
  headers: string[],
  rows: (string | DataTableCell | null)[][],
  colWidths: number[],
  options: DataTableOptions = {},
): number {
  const rowH = options.rowHeight || 20;
  const headerH = 22;
  const padding = 6;
  const fontSize = options.fontSize || 9;

  const totalRatio = colWidths.reduce((a, b) => a + b, 0);
  const actualWidths = colWidths.map((c) => (c / totalRatio) * w);
  let cy = y;

  // Header row — navy tinted
  drawRect(page, x, cy - headerH, w, headerH, { fill: rgb(0.93, 0.95, 0.97) });
  drawLine(page, x, cy - headerH, x + w, cy - headerH, COLORS.border, 0.5);
  let cx = x;
  for (let i = 0; i < headers.length; i++) {
    drawText(page, headers[i], cx + padding, cy - 14, fonts.semibold, fontSize, COLORS.accent, {
      maxWidth: actualWidths[i] - padding * 2,
    });
    cx += actualWidths[i];
  }
  cy -= headerH;

  // Data rows
  for (let r = 0; r < rows.length; r++) {
    const row = rows[r];
    if (cy - rowH < CONTENT_BOTTOM) break;
    if (r % 2 === 1) {
      drawRect(page, x, cy - rowH, w, rowH, { fill: COLORS.surface });
    }
    drawLine(page, x, cy - rowH, x + w, cy - rowH, rgb(0.92, 0.94, 0.96), 0.5);
    cx = x;
    for (let i = 0; i < row.length && i < actualWidths.length; i++) {
      const cell = row[i];
      const cellMaxW = actualWidths[i] - padding * 2;
      if (cell != null && typeof cell === "object" && "color" in cell) {
        drawText(
          page,
          (cell as DataTableCell).text,
          cx + padding,
          cy - 13,
          fonts.regular,
          fontSize,
          (cell as DataTableCell).color,
          { maxWidth: cellMaxW },
        );
      } else {
        drawText(page, String(cell ?? ""), cx + padding, cy - 13, fonts.regular, fontSize, COLORS.text, {
          maxWidth: cellMaxW,
        });
      }
      cx += actualWidths[i];
    }
    cy -= rowH;
  }

  const tableH = y - cy;
  drawRect(page, x, cy, w, tableH, { border: COLORS.border, borderWidth: 0.5 });
  cx = x;
  for (let i = 0; i < actualWidths.length - 1; i++) {
    cx += actualWidths[i];
    drawLine(page, cx, y, cx, cy, rgb(0.92, 0.94, 0.96), 0.5);
  }
  return y - cy;
}

// ─── Findings List ───────────────────────────────────────────────

interface Finding {
  label?: string;
  signal?: string;
  severity?: string;
  weight?: number;
}

function drawFindingsList(
  page: PDFPage,
  fonts: Fonts,
  x: number,
  y: number,
  findings: Finding[],
  maxWidth: number,
  maxCount = 30,
): number {
  const lineH = 16;
  let cy = y;
  const count = Math.min(findings.length, maxCount);

  for (let i = 0; i < count; i++) {
    if (cy - lineH < CONTENT_BOTTOM) break;
    const f = findings[i];
    const dotColor = severityColor(f.severity);
    page.drawCircle({ x: x + 4, y: cy - 4, size: 3, color: dotColor });

    const labelMaxW = maxWidth - 100;
    const label = safeText(f.label || f.signal || "");
    const lines = wrapText(fonts.regular, label, 9, labelMaxW);
    for (let l = 0; l < Math.min(lines.length, 2); l++) {
      drawText(page, lines[l], x + 14, cy - 5 - l * 12, fonts.regular, 9, COLORS.text, { maxWidth: labelMaxW });
    }

    const weight = f.weight || 1;
    const pipX = x + maxWidth - 60;
    for (let p = 0; p < 5; p++) {
      const filled = p < weight;
      page.drawCircle({
        x: pipX + p * 10,
        y: cy - 4,
        size: 3,
        color: filled ? dotColor : rgb(0.88, 0.9, 0.92),
        borderColor: filled ? dotColor : rgb(0.82, 0.85, 0.88),
        borderWidth: 0.5,
      });
    }

    const extraLines = Math.min(lines.length, 2) - 1;
    cy -= lineH + extraLines * 12;
  }
  return y - cy;
}

// ─── Section Header ──────────────────────────────────────────────

function drawSectionHeader(
  page: PDFPage,
  fonts: Fonts,
  y: number,
  title: string,
  score: number | undefined,
  weight: number | undefined,
  findingCount: number | undefined,
): number {
  const color = tierColor(tierFromScore(score));
  const tier = tierFromScore(score);

  // Left accent bar (3pt navy bar, positioned left of text with gap)
  const barGap = 8;
  drawRect(page, MARGIN - barGap - 3, y - 4, 3, 20, { fill: COLORS.accent });

  // Title
  drawText(page, title.toUpperCase(), MARGIN, y, fonts.bold, 14, COLORS.accent);

  // Score + tier on right
  if (score != null) {
    const scoreText = `${score} · ${tier}`;
    const sw = textWidth(fonts.bold, scoreText, 14);
    drawText(page, scoreText, PAGE_W - MARGIN - sw, y, fonts.bold, 14, color);
  }

  // Score bar
  const barY = y - 14;
  const barW = CONTENT_W;
  const barH = 4;
  drawRect(page, MARGIN, barY, barW, barH, { fill: rgb(0.92, 0.94, 0.96) });
  if (score != null) {
    drawRect(page, MARGIN, barY, barW * (score / 100), barH, { fill: color });
  }

  // Meta line
  const metaY = barY - 14;
  const meta = [];
  if (weight) meta.push(`Weight: ${Math.round(weight * 100)}% of composite`);
  if (score != null) meta.push(`Tier: ${tier}`);
  if (findingCount) meta.push(`${findingCount} findings`);
  drawText(page, meta.join("  |  "), MARGIN, metaY, fonts.regular, 9, COLORS.textSecondary);

  return y - metaY + 8;
}

// ─── Subsection Header ──────────────────────────────────────────

function drawSubsectionHeader(page: PDFPage, fonts: Fonts, y: number, title: string): number {
  // Left accent bar (positioned left of text with gap)
  drawRect(page, MARGIN - 6 - 2, y - 2, 2, 12, { fill: COLORS.accent, opacity: 0.5 });
  drawText(page, title.toUpperCase(), MARGIN, y, fonts.semibold, 10, COLORS.accent);
  return 20;
}

// ─── Status Indicator ────────────────────────────────────────────

function statusText(status: string | boolean): { text: string; color: Color } {
  if (status === "pass" || status === true || status === "good") return { text: "Pass", color: COLORS.good };
  if (status === "warn" || status === "warning" || status === "low" || status === "medium")
    return { text: "Warn", color: COLORS.moderate };
  if (status === "fail" || status === false || status === "high" || status === "critical")
    return { text: "Fail", color: COLORS.weak };
  if (status === "info") return { text: "Info", color: COLORS.info };
  return { text: String(status || "N/A"), color: COLORS.dim };
}

// ─── Checklist Grid ──────────────────────────────────────────────

interface ChecklistItem {
  label: string;
  status: boolean | null;
}

function drawChecklistGrid(
  page: PDFPage,
  fonts: Fonts,
  x: number,
  y: number,
  items: ChecklistItem[],
  maxWidth: number,
): number {
  const colW = maxWidth / 2;
  const rowH = 16;
  let cy = y;
  for (let i = 0; i < items.length; i += 2) {
    if (cy - rowH < CONTENT_BOTTOM) break;
    const left = items[i];
    if (left) {
      const color = left.status ? COLORS.good : left.status === false ? COLORS.weak : COLORS.moderate;
      page.drawCircle({ x: x + 4, y: cy - 4, size: 3, color });
      drawText(page, left.label, x + 14, cy - 7, fonts.regular, 9, COLORS.text, { maxWidth: colW - 20 });
    }
    const right = items[i + 1];
    if (right) {
      const color = right.status ? COLORS.good : right.status === false ? COLORS.weak : COLORS.moderate;
      page.drawCircle({ x: x + colW + 4, y: cy - 4, size: 3, color });
      drawText(page, right.label, x + colW + 14, cy - 7, fonts.regular, 9, COLORS.text, { maxWidth: colW - 20 });
    }
    cy -= rowH;
  }
  return y - cy;
}

// ─── Format Helpers ──────────────────────────────────────────────

function formatMs(ms: number | null | undefined): string {
  if (ms == null) return "N/A";
  if (ms >= 1000) return `${(ms / 1000).toFixed(1)}s`;
  return `${Math.round(ms)}ms`;
}

function formatDate(dateStr: string | null | undefined): string {
  if (!dateStr) return "N/A";
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return String(dateStr);
  }
}

function severityImpact(severity: string | undefined): number {
  const map: Record<string, number> = { good: 0, info: 0.2, low: 0.5, medium: 0.75, high: 1.0, critical: 1.5 };
  return (severity ? map[severity] : undefined) ?? 0;
}

// ═══════════════════════════════════════════════════════════════════
// PAGE BUILDERS
// ═══════════════════════════════════════════════════════════════════

function buildPage1(doc: PDFDocument, fonts: Fonts, data: AnalysisData): PDFPage {
  const page = doc.addPage([PAGE_W, PAGE_H]);
  const ds = data.domain_score;
  const composite = ds.composite;
  const tier = ds.tier || tierFromScore(composite);
  const archetype = ds.archetype?.detected || "General";
  const color = tierColor(tier);

  drawPageHeader(page, fonts, REPORT_CONFIG.brandTagline);

  let y = CONTENT_TOP;

  // ── Domain name (monospace) ──
  const domainDisplay = truncateText(fonts.mono, data.domain, 18, CONTENT_W - 130);
  drawText(page, domainDisplay, MARGIN, y, fonts.mono, 18, COLORS.text, { maxWidth: CONTENT_W - 130 });

  // ── Score Badge (right side) — tier name + score ──
  const badgeW = 90;
  const badgeH = 72;
  const badgeX = PAGE_W - MARGIN - badgeW;
  const badgeY = y - badgeH + 16;

  // Badge background (12% tier color fill)
  drawRect(page, badgeX, badgeY, badgeW, badgeH, {
    fill: color,
    border: color,
    borderWidth: 2,
    opacity: 0.12,
    borderOpacity: 0.6,
  });

  // Score number (large) — vertically centered in upper portion
  const scoreStr = String(composite);
  const scoreW = textWidth(fonts.bold, scoreStr, 36);
  drawText(page, scoreStr, badgeX + (badgeW - scoreW) / 2, badgeY + 32, fonts.bold, 36, color);

  // Tier label (below score)
  const tierW = textWidth(fonts.semibold, tier, 10);
  drawText(page, tier, badgeX + (badgeW - tierW) / 2, badgeY + 12, fonts.semibold, 10, color);

  // ── Meta info ──
  y -= 26;
  drawText(page, `Analyzed: ${formatDate(data.analyzed_at)}`, MARGIN, y, fonts.regular, 10, COLORS.textSecondary);
  y -= 16;
  drawText(
    page,
    `Archetype: ${archetype.charAt(0).toUpperCase() + archetype.slice(1)}`,
    MARGIN,
    y,
    fonts.regular,
    10,
    COLORS.textSecondary,
  );

  y -= 30;

  // ── Two-column layout: Radar chart | Axis scores ──
  const leftW = 230;
  const rightW = CONTENT_W - leftW - 16;
  const rightX = MARGIN + leftW + 16;

  const radarCx = MARGIN + leftW / 2;
  const radarCy = y - 95;
  const radarR = 58;
  drawRadarChart(page, fonts, ds.axes, radarCx, radarCy, radarR);

  // Axis scores (right column)
  let axisY = y - 10;
  drawText(page, "AXIS SCORES", rightX, axisY, fonts.semibold, 10, COLORS.accent);
  axisY -= 6;
  drawLine(page, rightX, axisY, rightX + rightW, axisY, COLORS.border, 0.5);
  axisY -= 18;

  for (const axis of AXIS_ORDER) {
    const ax = ds.axes[axis];
    if (!ax) continue;
    const score = ax.score;
    const axTier = tierFromScore(score);
    const axColor = tierColor(axTier);

    drawText(page, AXIS_LABELS[axis], rightX, axisY, fonts.regular, 10, COLORS.textSecondary, { maxWidth: 110 });

    // Score bar
    const barX = rightX + 115;
    const barW = rightW - 185;
    drawRect(page, barX, axisY - 1, barW, 8, { fill: rgb(0.92, 0.94, 0.96) });
    drawRect(page, barX, axisY - 1, barW * (score / 100), 8, { fill: axColor, opacity: 0.7 });

    // Score + tier
    const scoreTier = `${score}  ${axTier}`;
    const stW = textWidth(fonts.semibold, scoreTier, 10);
    drawText(page, scoreTier, rightX + rightW - stW, axisY, fonts.semibold, 10, axColor);

    axisY -= 26;
  }

  // ── Top Findings ──
  y = Math.min(axisY - 10, radarCy - radarR - 50);
  drawText(page, "TOP FINDINGS", MARGIN, y, fonts.semibold, 11, COLORS.accent);
  y -= 4;
  drawLine(page, MARGIN, y, PAGE_W - MARGIN, y, COLORS.border, 0.5);
  y -= 14;

  // Gather all findings, sort by weight * severity impact
  const allFindings = [];
  for (const axis of AXIS_ORDER) {
    const ax = ds.axes[axis];
    if (!ax) continue;
    for (const f of ax.findings) {
      allFindings.push({ ...f, axisName: AXIS_LABELS[axis] });
    }
  }
  allFindings.sort((a, b) => b.weight * severityImpact(b.severity) - a.weight * severityImpact(a.severity));

  const goodFindings = allFindings.filter((f) => f.severity === "good").slice(0, 4);
  const badFindings = allFindings.filter((f) => f.severity !== "good" && f.severity !== "info").slice(0, 6);
  const finalFindings = [...badFindings, ...goodFindings].slice(0, 10);

  for (const f of finalFindings) {
    if (y < CONTENT_BOTTOM + 10) break;
    const dotColor = severityColor(f.severity);
    page.drawCircle({ x: MARGIN + 4, y: y - 2, size: 3, color: dotColor });

    const label = safeText(f.label);
    const axisTag = f.axisName;
    const tagW = textWidth(fonts.regular, axisTag, 8);
    const labelMaxW = CONTENT_W - 30 - tagW - 10;

    drawText(page, label, MARGIN + 14, y - 5, fonts.regular, 9.5, COLORS.text, { maxWidth: labelMaxW });
    drawText(page, axisTag, PAGE_W - MARGIN - tagW, y - 5, fonts.regular, 8, COLORS.textSecondary);
    y -= 16;
  }

  // Legend
  if (y > CONTENT_BOTTOM + 10) {
    y -= 8;
    drawText(page, "Legend:", MARGIN, y, fonts.regular, 8, COLORS.dim);
    page.drawCircle({ x: MARGIN + 40, y: y + 2, size: 2.5, color: COLORS.good });
    drawText(page, "= positive", MARGIN + 46, y - 1, fonts.regular, 7.5, COLORS.dim);
    page.drawCircle({ x: MARGIN + 100, y: y + 2, size: 2.5, color: COLORS.moderate });
    drawText(page, "= needs attention", MARGIN + 106, y - 1, fonts.regular, 7.5, COLORS.dim);
    page.drawCircle({ x: MARGIN + 185, y: y + 2, size: 2.5, color: COLORS.weak });
    drawText(page, "= critical", MARGIN + 191, y - 1, fonts.regular, 7.5, COLORS.dim);
  }

  return page;
}

function buildPage2_Security(doc: PDFDocument, fonts: Fonts, data: AnalysisData): PDFPage {
  const page = doc.addPage([PAGE_W, PAGE_H]);
  drawPageHeader(page, fonts, "Security Detail");

  const ds = data.domain_score;
  const secAxis = ds.axes.security;
  let y = CONTENT_TOP;

  const hdrH = drawSectionHeader(
    page,
    fonts,
    y,
    "Security",
    secAxis?.score,
    AXIS_WEIGHTS.security,
    secAxis?.findings?.length,
  );
  y -= hdrH + 8;

  // ── SSL/TLS Card ──
  const ssl = data.ssl || {};
  const sslH = drawSubsectionHeader(page, fonts, y, "SSL / TLS");
  y -= sslH;

  const sslGrade = ssl.grade || "N/A";
  const sslIssuer = (ssl.issuer || "N/A").split(",")[0].replace("CN=", "");
  const sslProtocols = (ssl.protocols || []).join(", ") || "N/A";
  const sslExpires = formatDate(ssl.valid_to);
  const hsts = data.headers?.security_audit?.find((h: any) => h.header === "Strict-Transport-Security");
  const hstsStatus = hsts ? (hsts.status === "pass" ? "Enabled" : "Missing") : "N/A";
  const caa = data.caa_analysis;
  const caaIssuers =
    caa?.records
      ?.filter((r: any) => r.tag === "issue")
      .map((r: any) => r.ca_name || r.value)
      .join(", ") || "N/A";

  const sslRows = [
    [`SSL: ${sslGrade}`, `Issuer: ${sslIssuer}`],
    [`Protocols: ${sslProtocols}`, `Expires: ${sslExpires}`],
    [`HSTS: ${hstsStatus}`, `CAA: ${truncateText(fonts.regular, caaIssuers, 9, 180)}`],
  ];
  const cardH = drawSummaryCard(page, fonts, MARGIN, y, CONTENT_W, sslRows);
  y -= cardH + 14;

  // ── Security Headers Table ──
  const shH = drawSubsectionHeader(page, fonts, y, "Security Headers");
  y -= shH;

  const secHeaders = data.headers?.security_audit || [];
  const headerRows = secHeaders.map((h: any) => {
    const st = statusText(h.status);
    return [
      { text: st.text, color: st.color },
      h.header || "",
      h.value ? (h.value.length > 60 ? `${h.value.slice(0, 57)}...` : h.value) : "Not set",
      h.recommendation || "\u2014",
    ];
  });

  const tableH = drawDataTable(
    page,
    fonts,
    MARGIN,
    y,
    CONTENT_W,
    ["Status", "Header", "Value", "Recommendation"],
    headerRows,
    [1, 2.5, 4, 3],
    { fontSize: 8, rowHeight: 18 },
  );
  y -= tableH + 14;

  // ── Email Auth Card ──
  if (y > CONTENT_BOTTOM + 100) {
    const eaH = drawSubsectionHeader(page, fonts, y, "Email Authentication");
    y -= eaH;

    const ea = data.email_auth || {};
    const spfStatus = ea.spf?.found ? "Pass" : "Not found";
    const dmarcStatus = ea.dmarc?.found ? `p=${ea.dmarc.policy}` : "Not found";
    const dkimStatus = ea.dkim_selectors_found?.length ? `${ea.dkim_selectors_found.length} selectors` : "Not found";
    const bimiStatus = ea.bimi?.found ? "Found" : "Not found";
    const mtaSts = ea.mta_sts?.dns_found ? ea.mta_sts.mode || "Found" : "Not found";
    const tlsRpt = ea.tls_rpt?.found ? "Configured" : "Not found";

    const emailRows = [
      [`SPF: ${spfStatus}`, `DMARC: ${dmarcStatus}`],
      [`DKIM: ${dkimStatus}`, `BIMI: ${bimiStatus}`],
      [`MTA-STS: ${mtaSts}`, `TLS-RPT: ${tlsRpt}`],
    ];
    const emailCardH = drawSummaryCard(page, fonts, MARGIN, y, CONTENT_W, emailRows);
    y -= emailCardH + 14;
  }

  // ── Security Findings ──
  if (y > CONTENT_BOTTOM + 40) {
    const fH = drawSubsectionHeader(page, fonts, y, "All Security Findings");
    y -= fH;
    const findings = secAxis?.findings || [];
    const sorted = [...findings].sort(
      (a, b) => severityImpact(b.severity) * b.weight - severityImpact(a.severity) * a.weight,
    );
    drawFindingsList(page, fonts, MARGIN, y, sorted, CONTENT_W);
  }

  return page;
}

function buildPage3_SpeedFoundations(doc: PDFDocument, fonts: Fonts, data: AnalysisData): PDFPage {
  const page = doc.addPage([PAGE_W, PAGE_H]);
  drawPageHeader(page, fonts, "Speed & Foundations");

  const ds = data.domain_score;
  let y = CONTENT_TOP;

  // ── Speed Section ──
  const speedAxis = ds.axes.speed;
  const hdrH = drawSectionHeader(
    page,
    fonts,
    y,
    "Speed",
    speedAxis?.score,
    AXIS_WEIGHTS.speed,
    speedAxis?.findings?.length,
  );
  y -= hdrH + 8;

  const cwvH = drawSubsectionHeader(page, fonts, y, "Core Web Vitals");
  y -= cwvH;

  const perf = data.performance || {};
  const perfD = data.performance_desktop || {};
  const crux = data.performance_crux || {};

  const cwvMetrics = [
    { key: "LCP", mobile: perf.lcp, desktop: perfD.lcp, unit: "ms", goodThresh: 2500, poorThresh: 4000 },
    { key: "FCP", mobile: perf.fcp, desktop: perfD.fcp, unit: "ms", goodThresh: 1800, poorThresh: 3000 },
    { key: "CLS", mobile: perf.cls, desktop: perfD.cls, unit: "", goodThresh: 0.1, poorThresh: 0.25 },
    { key: "TBT", mobile: perf.tbt, desktop: perfD.tbt, unit: "ms", goodThresh: 200, poorThresh: 600 },
    { key: "TTFB", mobile: perf.ttfb, desktop: perfD.ttfb, unit: "ms", goodThresh: 800, poorThresh: 1800 },
  ];

  const cwvRows = cwvMetrics.map((m) => {
    const mVal = m.mobile != null ? (m.unit === "ms" ? formatMs(m.mobile) : m.mobile.toFixed(2)) : "N/A";
    const dVal = m.desktop != null ? (m.unit === "ms" ? formatMs(m.desktop) : m.desktop.toFixed(2)) : "N/A";
    const blendVal =
      m.mobile != null && m.desktop != null
        ? m.unit === "ms"
          ? formatMs(m.mobile * 0.6 + m.desktop * 0.4)
          : (m.mobile * 0.6 + m.desktop * 0.4).toFixed(2)
        : "N/A";
    const refVal = m.mobile ?? m.desktop ?? null;
    let status: { text: string; color: Color };
    if (refVal == null) status = { text: "N/A", color: COLORS.dim };
    else if (refVal <= m.goodThresh) status = { text: "Good", color: COLORS.good };
    else if (refVal <= m.poorThresh) status = { text: "Needs work", color: COLORS.moderate };
    else status = { text: "Poor", color: COLORS.weak };

    // Metric name with explainer
    const nameCol = `${m.key}`;
    return [nameCol, mVal, dVal, blendVal, status];
  });

  const cwvTableH = drawDataTable(
    page,
    fonts,
    MARGIN,
    y,
    CONTENT_W,
    ["Metric", "Mobile", "Desktop", "Blended", "Status"],
    cwvRows,
    [1.2, 1, 1, 1, 1.2],
    { fontSize: 9 },
  );
  y -= cwvTableH + 14;

  // Acronym explainers below the table — two-column layout
  if (y > CONTENT_BOTTOM + 40) {
    const colW = (CONTENT_W - 16) / 2;
    const explainers = cwvMetrics.map((m) => CWV_EXPLAINERS[m.key]).filter((e): e is string => !!e);
    for (let i = 0; i < explainers.length; i += 2) {
      drawText(page, explainers[i], MARGIN + 4, y, fonts.regular, 7, COLORS.dim, { maxWidth: colW - 8 });
      if (i + 1 < explainers.length) {
        drawText(page, explainers[i + 1], MARGIN + colW + 12, y, fonts.regular, 7, COLORS.dim, {
          maxWidth: colW - 8,
        });
      }
      y -= 10;
    }
    y -= 4;
  }

  // PageSpeed scores
  if (y > CONTENT_BOTTOM + 30) {
    const mobileScore = perf.score != null ? `Mobile ${perf.score}` : "Mobile N/A";
    const desktopScore = perfD.score != null ? `Desktop ${perfD.score}` : "Desktop N/A";
    drawText(
      page,
      `PageSpeed Scores: ${mobileScore} / ${desktopScore}`,
      MARGIN,
      y,
      fonts.medium,
      9,
      COLORS.textSecondary,
    );
    y -= 16;
    if (crux.has_data) {
      const period = crux.collection_period;
      drawText(
        page,
        `CrUX Field Data: Available (${formatDate(period?.first_date)} - ${formatDate(period?.last_date)})`,
        MARGIN,
        y,
        fonts.regular,
        9,
        COLORS.textSecondary,
      );
      y -= 16;
    }
    y -= 8;
  }

  // ── Foundations Section ──
  if (y > CONTENT_BOTTOM + 120) {
    const foundAxis = ds.axes.foundations;
    const fhdrH = drawSectionHeader(
      page,
      fonts,
      y,
      "Foundations",
      foundAxis?.score,
      AXIS_WEIGHTS.foundations,
      foundAxis?.findings?.length,
    );
    y -= fhdrH + 8;

    const infraH = drawSubsectionHeader(page, fonts, y, "Infrastructure");
    y -= infraH;

    const hosting = data.hosting || {};
    const httpProto = data.http_protocols || {};
    const dnssec = data.dnssec || {};
    const waf = data.waf || {};
    const status = data.status || {};
    const lastRedirect = (data.redirects || []).slice(-1)[0];
    const responseTime = status.response_time_ms || lastRedirect?.response_time_ms;

    const infraRows = [
      [`Hosting: ${hosting.provider || "N/A"}`, `CDN: ${hosting.cdn || "Not detected"}`],
      [`HTTP/2: ${httpProto.http2 ? "Yes" : "No"}`, `HTTP/3: ${httpProto.http3 ? "Yes" : "No"}`],
      [
        `WAF: ${waf.detected ? waf.provider || "Detected" : "Not detected"}`,
        `DNSSEC: ${dnssec.enabled ? "Enabled" : "Not enabled"}`,
      ],
      [`Response Time: ${formatMs(responseTime)}`, `IPv6: ${data.dns?.AAAA?.length ? "Yes" : "No"}`],
    ];
    const infraCardH = drawSummaryCard(page, fonts, MARGIN, y, CONTENT_W, infraRows);
    y -= infraCardH + 14;

    if (y > CONTENT_BOTTOM + 60) {
      const comp = data.compression || {};
      const cache = data.cache_analysis || {};
      const cacheCtrl = cache.cache_control?.raw || "Not set";
      const encoding = comp.encoding || "None detected";

      const ccH = drawSubsectionHeader(page, fonts, y, "Cache & Compression");
      y -= ccH;
      const ccRows = [[`Encoding: ${encoding}`, `Cache-Control: ${truncateText(fonts.regular, cacheCtrl, 9, 180)}`]];
      const ccCardH = drawSummaryCard(page, fonts, MARGIN, y, CONTENT_W, ccRows);
      y -= ccCardH + 14;
    }

    if (y > CONTENT_BOTTOM + 40) {
      const fH = drawSubsectionHeader(page, fonts, y, "Foundations Findings");
      y -= fH;
      const findings = foundAxis?.findings || [];
      const sorted = [...findings].sort(
        (a, b) => severityImpact(b.severity) * b.weight - severityImpact(a.severity) * a.weight,
      );
      drawFindingsList(page, fonts, MARGIN, y, sorted, CONTENT_W, 15);
    }
  }

  return page;
}

function buildPage4_ReputationDiscoverabilityEmail(doc: PDFDocument, fonts: Fonts, data: AnalysisData): PDFPage {
  const page = doc.addPage([PAGE_W, PAGE_H]);
  drawPageHeader(page, fonts, "Reputation, Discoverability & Email");

  const ds = data.domain_score;
  let y = CONTENT_TOP;

  // ── Reputation ──
  const repAxis = ds.axes.reputation;
  const rH = drawSectionHeader(
    page,
    fonts,
    y,
    "Reputation",
    repAxis?.score,
    AXIS_WEIGHTS.reputation,
    repAxis?.findings?.length,
  );
  y -= rH + 8;

  const tH = drawSubsectionHeader(page, fonts, y, "Trust Signals");
  y -= tH;

  const legal = data.legal || {};
  const secTxt = data.security_txt || {};
  const tranco = data.tranco_rank;
  const cookieConsent = data.cookie_consent;
  const ssl = data.ssl || {};
  const pagesFound = (legal.pages_found || []).map((p: any) => p.name);

  const trustItems = [
    { label: "Privacy Policy", status: pagesFound.includes("Privacy Policy") },
    { label: "Terms of Service", status: pagesFound.includes("Terms of Service") },
    { label: "About page", status: pagesFound.includes("About") || pagesFound.includes("Team") },
    { label: "security.txt published", status: secTxt.found === true },
    {
      label: secTxt.contact?.[0]?.includes("hackerone") ? "Bug Bounty (HackerOne)" : "Bug bounty program",
      status: secTxt.contact?.[0]?.includes("hackerone") || secTxt.contact?.[0]?.includes("bugcrowd") || false,
    },
    {
      label: tranco ? `Tranco rank: ${tranco.toLocaleString()}` : "Tranco rank: Unranked",
      status: tranco && tranco < 100000,
    },
    {
      label: `Certificate: ${ssl.issuer?.includes("DigiCert") ? "OV" : "DV"}`,
      status: ssl.issuer?.includes("DigiCert") || false,
    },
    {
      label: cookieConsent?.cmp_detected ? "Cookie consent detected" : "No cookie consent",
      status: !!cookieConsent?.cmp_detected,
    },
  ];

  const checkH = drawChecklistGrid(page, fonts, MARGIN, y, trustItems, CONTENT_W);
  y -= checkH + 12;

  // Breach history
  if (y > CONTENT_BOTTOM + 50) {
    const bH = drawSubsectionHeader(page, fonts, y, "Data Breach History");
    y -= bH;

    const breaches = data.breaches || {};
    if (!breaches.found || !breaches.breaches?.length) {
      drawRect(page, MARGIN, y - 30, CONTENT_W, 30, { fill: COLORS.surface, border: COLORS.border, borderWidth: 0.5 });
      drawText(
        page,
        "No breaches found in Have I Been Pwned database.",
        MARGIN + 10,
        y - 20,
        fonts.regular,
        9,
        COLORS.good,
      );
      y -= 44;
    } else {
      for (const b of breaches.breaches.slice(0, 3)) {
        if (y < CONTENT_BOTTOM + 40) break;
        const title = truncateText(
          fonts.medium,
          `${b.title || b.Name || "Unknown"} (${formatDate(b.date || b.BreachDate)}) - ${(b.count || b.PwnCount || 0).toLocaleString()} records`,
          9,
          CONTENT_W - 20,
        );
        drawText(page, title, MARGIN + 10, y - 5, fonts.medium, 9, COLORS.text, { maxWidth: CONTENT_W - 20 });
        y -= 14;
        const classes = (b.data_classes || b.DataClasses || []).join(", ");
        if (classes) {
          drawText(
            page,
            `Compromised: ${truncateText(fonts.regular, classes, 8, CONTENT_W - 100)}`,
            MARGIN + 10,
            y - 5,
            fonts.regular,
            8,
            COLORS.textSecondary,
            { maxWidth: CONTENT_W - 20 },
          );
          y -= 14;
        }
        y -= 4;
      }
      y -= 8;
    }
  }

  // ── Discoverability ──
  if (y > CONTENT_BOTTOM + 120) {
    const discAxis = ds.axes.discoverability;
    const dH = drawSectionHeader(
      page,
      fonts,
      y,
      "Discoverability",
      discAxis?.score,
      AXIS_WEIGHTS.discoverability,
      discAxis?.findings?.length,
    );
    y -= dH + 8;

    const tsH = drawSubsectionHeader(page, fonts, y, "Technology Stack");
    y -= tsH;

    const techStack = data.tech_stack || [];
    if (techStack.length > 0) {
      const tsRows = techStack
        .slice(0, 8)
        .map((t: any) => [
          t.category || "Unknown",
          t.name || "Unknown",
          t.confidence ? t.confidence.charAt(0).toUpperCase() + t.confidence.slice(1) : "N/A",
        ]);
      const tsTableH = drawDataTable(
        page,
        fonts,
        MARGIN,
        y,
        CONTENT_W,
        ["Category", "Technology", "Confidence"],
        tsRows,
        [2, 2, 1],
        { fontSize: 9 },
      );
      y -= tsTableH + 12;
    }

    if (y > CONTENT_BOTTOM + 60) {
      const seoH = drawSubsectionHeader(page, fonts, y, "SEO & Social Readiness");
      y -= seoH;

      const socialMeta = data.social_meta || {};
      const aiReady = data.ai_readiness || {};
      const robots = data.robots_parsed;
      const sitemap = data.meta?.sitemap_detected;

      const seoItems = [
        { label: `Open Graph: ${socialMeta.og?.title ? "Complete" : "Missing"}`, status: !!socialMeta.og?.title },
        {
          label: `Twitter Card: ${socialMeta.twitter_card?.card ? "Present" : "Missing"}`,
          status: !!socialMeta.twitter_card?.card,
        },
        { label: `robots.txt: ${robots ? "Present" : "Not found"}`, status: !!robots },
        { label: `Sitemap: ${sitemap ? "Detected" : "Not detected"}`, status: !!sitemap },
        {
          label: `AI Readiness: ${aiReady.score || 0}/${aiReady.max_score || 100}`,
          status: (aiReady.score || 0) >= 50,
        },
        {
          label: `Structured Data: ${data.structured_data?.types?.length ? data.structured_data.types.join(", ") : data.json_ld?.length ? "Present" : "Not found"}`,
          status: !!(data.structured_data?.types?.length || data.json_ld?.length),
        },
      ];
      drawChecklistGrid(page, fonts, MARGIN, y, seoItems, CONTENT_W);
    }
  }

  return page;
}

// ═══════════════════════════════════════════════════════════════════
// PAGE 5 — SCORE BREAKDOWN
// ═══════════════════════════════════════════════════════════════════

function buildPage5_ScoreBreakdown(doc: PDFDocument, fonts: Fonts, data: AnalysisData): PDFPage[] {
  const pages = [];
  let page = doc.addPage([PAGE_W, PAGE_H]);
  pages.push(page);
  drawPageHeader(page, fonts, "Score Breakdown");

  const ds = data.domain_score;
  const composite = ds.composite;
  const tier = ds.tier || tierFromScore(composite);
  const color = tierColor(tier);
  let y = CONTENT_TOP;

  // ── Section title ──
  drawRect(page, MARGIN - 8 - 3, y - 4, 3, 20, { fill: COLORS.accent });
  drawText(page, "SCORE BREAKDOWN", MARGIN, y, fonts.bold, 14, COLORS.accent);
  y -= 28;

  // ── Composite formula: SEC 85×.24 + SPD 88×.18 + ... = 89 ──
  const formulaParts = [];
  for (const axis of AXIS_ORDER) {
    const ax = ds.axes[axis];
    if (!ax) continue;
    const w = AXIS_WEIGHTS[axis];
    formulaParts.push(`${AXIS_ABBR[axis]} ${ax.score}×${w.toFixed(2)}`);
  }
  const formulaStr = `${formulaParts.join("  +  ")} = ${composite}`;

  // Draw formula in mono — may be long, so truncate if needed
  drawText(page, formulaStr, MARGIN, y, fonts.mono, 7.5, COLORS.text, { maxWidth: CONTENT_W });
  y -= 30;

  // ── Tier Progress Bar ──
  const barW = CONTENT_W;
  const barH = 16;
  const barY = y - barH;

  // Draw tier segments
  for (const td of TIER_DEFS) {
    const segX = MARGIN + (td.min / 100) * barW;
    const segW = ((td.max - td.min) / 100) * barW;
    drawRect(page, segX, barY, segW, barH, { fill: td.color, opacity: 0.15 });
    // Tier label inside segment
    const labelW = textWidth(fonts.regular, td.tier, 6.5);
    if (segW > labelW + 4) {
      drawText(page, td.tier, segX + (segW - labelW) / 2, barY + 5, fonts.regular, 6.5, td.color);
    }
  }
  drawRect(page, MARGIN, barY, barW, barH, { border: COLORS.border, borderWidth: 0.5 });

  // Score indicator — small triangle above
  const indicatorX = MARGIN + (composite / 100) * barW;
  // Draw a triangle pointing down
  const triSize = 4;
  const triTop = barY + barH + triSize + 1;
  page.drawSvgPath(`M 0,0 L ${triSize},-${triSize * 1.5} L ${-triSize},-${triSize * 1.5} Z`, {
    x: indicatorX,
    y: triTop,
    color: color,
  });
  // Score label above indicator — clear gap above triangle
  const scoreLabel = `${composite} · ${tier}`;
  const slW = textWidth(fonts.bold, scoreLabel, 8);
  const labelX = Math.max(MARGIN, Math.min(indicatorX - slW / 2, PAGE_W - MARGIN - slW));
  drawText(page, scoreLabel, labelX, triTop + 10, fonts.bold, 8, color);

  y = barY - 12;

  // ── Per-axis deduction breakdowns ──
  // Sort by composite impact (weight * deduction) — highest first
  const axisData = AXIS_ORDER.map((axis) => {
    const ax = ds.axes[axis];
    if (!ax) return null;
    const totalDeduction = 100 - ax.score;
    const compositeImpact = totalDeduction * (AXIS_WEIGHTS[axis] || 0);
    return { axis, score: ax.score, totalDeduction, compositeImpact, deductions: ax.deductions || [] };
  }).filter((x): x is NonNullable<typeof x> => x != null);

  axisData.sort((a, b) => b.compositeImpact - a.compositeImpact);

  for (const axInfo of axisData) {
    const axScore = axInfo.score;
    const axTier = tierFromScore(axScore);
    const axColor = tierColor(axTier);
    const axLabel = AXIS_LABELS[axInfo.axis];
    const axWeight = AXIS_WEIGHTS[axInfo.axis];

    // Check if we need a new page
    if (y < CONTENT_BOTTOM + 60) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      pages.push(page);
      drawPageHeader(page, fonts, "Score Breakdown (continued)");
      y = CONTENT_TOP;
    }

    // Axis header line
    drawRect(page, MARGIN - 6 - 2, y - 2, 2, 12, { fill: axColor });
    drawText(page, `${axLabel}`, MARGIN, y, fonts.semibold, 10, COLORS.text);

    const deductionTotal = axInfo.totalDeduction;
    const metaText = `${axScore} · ${axTier}  |  ${Math.round(axWeight * 100)}% weight  |  -${deductionTotal.toFixed(1)} points`;
    const mtW = textWidth(fonts.regular, metaText, 8);
    drawText(page, metaText, PAGE_W - MARGIN - mtW, y + 1, fonts.regular, 8, axColor);
    y -= 18;

    // Collect signals from deductions
    const issues = []; // fixable: deduction > 0, not absent
    const opportunities = []; // absent + actionable
    const notAssessed = []; // absent + not actionable

    for (const ded of axInfo.deductions) {
      if (ded.signal === "_absent" && ded.absentSignals) {
        for (const abs of ded.absentSignals) {
          const item = {
            signal: abs.signal,
            label: abs.absentLabel || abs.label,
            deduction: abs.deduction || 0,
            weight: abs.weight || 1,
            effort: abs.effort,
            fixDescription: abs.fixDescription,
            actionable: abs.actionable !== false,
          };
          if (item.actionable) {
            opportunities.push(item);
          } else {
            notAssessed.push(item);
          }
        }
      } else if (ded.deduction > 0) {
        issues.push({
          signal: ded.signal,
          label: ded.label,
          deduction: ded.deduction,
          weight: ded.weight || 1,
          severity: ded.severity,
          effort: ded.effort,
          fixDescription: ded.fixDescription,
        });
      }
    }

    // Sort each group by deduction desc
    issues.sort((a, b) => b.deduction - a.deduction);
    opportunities.sort((a, b) => b.deduction - a.deduction);
    notAssessed.sort((a, b) => b.deduction - a.deduction);

    // Draw signal groups
    const groups = [
      { title: "Issues", items: issues, dotColor: COLORS.weak },
      { title: "Improvements", items: opportunities, dotColor: COLORS.moderate },
      { title: "Not Assessed", items: notAssessed, dotColor: COLORS.absent },
    ];

    for (const group of groups) {
      if (group.items.length === 0) continue;

      if (y < CONTENT_BOTTOM + 30) {
        page = doc.addPage([PAGE_W, PAGE_H]);
        pages.push(page);
        drawPageHeader(page, fonts, "Score Breakdown (continued)");
        y = CONTENT_TOP;
      }

      // Group label
      drawText(page, group.title, MARGIN + 12, y, fonts.medium, 8, COLORS.textSecondary);
      y -= 12;

      for (const item of group.items) {
        if (y < CONTENT_BOTTOM + 14) {
          page = doc.addPage([PAGE_W, PAGE_H]);
          pages.push(page);
          drawPageHeader(page, fonts, "Score Breakdown (continued)");
          y = CONTENT_TOP;
        }

        // Severity dot
        page.drawCircle({ x: MARGIN + 16, y: y - 2, size: 2.5, color: group.dotColor });

        // Label (truncated to fit)
        const label = safeText(item.label || item.signal);
        const deductStr = item.deduction > 0 ? `-${item.deduction.toFixed(1)}` : "0";
        const deductW = textWidth(fonts.mono, deductStr, 8);

        const labelMaxW = CONTENT_W - 32 - deductW - 12;
        drawText(page, label, MARGIN + 24, y - 4, fonts.regular, 8.5, COLORS.text, { maxWidth: labelMaxW });

        // Deduction amount (right-aligned, monospace)
        const dedX = PAGE_W - MARGIN - deductW;
        drawText(page, deductStr, dedX, y - 4, fonts.mono, 8, item.deduction > 0 ? COLORS.weak : COLORS.dim);

        y -= 14;
      }
      y -= 4;
    }

    // If no deductions at all
    if (issues.length === 0 && opportunities.length === 0 && notAssessed.length === 0) {
      drawText(page, "No deductions — perfect score in this axis.", MARGIN + 12, y, fonts.regular, 8.5, COLORS.good);
      y -= 14;
    }

    y -= 8; // Spacing between axes
  }

  return pages;
}

// ═══════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════

// ─── Main Export ─────────────────────────────────────────────────

export async function generatePdfReport(data: AnalysisData, fontData: PdfFontData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  doc.setTitle(`Yoke Domain Intelligence Report — ${data.domain}`);
  doc.setAuthor(REPORT_CONFIG.footerUrl);
  doc.setSubject(`Domain analysis report for ${data.domain}`);
  doc.setCreationDate(new Date());

  // Load fonts from KV-sourced binary data
  const fonts: Fonts = {
    regular: await doc.embedFont(fontData.interRegular),
    medium: await doc.embedFont(fontData.interMedium),
    semibold: await doc.embedFont(fontData.interSemiBold),
    bold: await doc.embedFont(fontData.interBold),
    mono: await doc.embedFont(fontData.jetBrainsMono),
  };

  // Build pages
  const allPages: PDFPage[] = [];
  allPages.push(buildPage1(doc, fonts, data));
  allPages.push(buildPage2_Security(doc, fonts, data));
  allPages.push(buildPage3_SpeedFoundations(doc, fonts, data));
  allPages.push(buildPage4_ReputationDiscoverabilityEmail(doc, fonts, data));

  // Page 5 may return multiple pages
  const breakdownPages = buildPage5_ScoreBreakdown(doc, fonts, data);
  allPages.push(...breakdownPages);

  // Add page footers with correct total
  const totalPages = allPages.length;
  for (let i = 0; i < totalPages; i++) {
    drawPageFooter(allPages[i], fonts, i + 1, totalPages);
  }

  return doc.save();
}
